version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 99
    allow:
    - dependency-type: direct
    - dependency-type: indirect
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 99
    versioning-strategy: lockfile-only
